version: '3.9'
services:
  db:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: "productosdb"
      MYSQL_USER: "admin"
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_PASSWORD: "123456"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: